
name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    - name: Install MXE build environment
      #&& sudo add-apt-repository "deb [arch=amd64] https://pkg.mxe.cc/repos/apt `lsb_release -sc` main" 
      run: >
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9 
        && sudo add-apt-repository "deb [arch=amd64] https://pkg.mxe.cc/repos/apt focal main" 
        && sudo apt-get update
        && sudo apt install mxe-x86-64-w64-mingw32.static-cc mxe-x86-64-w64-mingw32.static-glib
        
    - name: Check MXE installation
      run: >
        ls /usr/lib/
        && /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cc --version
    # - name: Install chafa
    #   run: >
    #     sudo apt-get install chafa;
    #     sudo ldconfig;

    - name: Build glib with MXE
      run: >
        cd /usr/lib/mxe/
        && sudo make settings.mk
        && sudo make glib
      #./configure --host=i686-w64-mingw32.static --enable-static --disable-shared
      #make

    # meson.build:2422:26: ERROR: python is missing modules: packaging
    #- name: Install tools for building C
    #  run: >
    #    sudo pipx install meson
    #    && sudo pipx install packaging
    #    && sudo apt-get install ninja-build
    #    
    #- name: Download glib source
    #  run: >
    #    cd /tmp/ &&
    #    curl 'https://download.gnome.org/sources/glib/2.80/glib-2.80.0.tar.xz' -L -O &&
    #    ls

    #- name: Build glib
    #  working-directory: /tmp/
    #  run: >
    #    tar xf glib-2.80.0.tar.xz
    #    && cd glib-2.80.0/
    #    && meson setup _build
    #    && meson compile -C _build
    #    && meson install -C _build 

    #- name: Check chafa installation
    #  run: >
    #    export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig";
    #    echo $(ls /usr/local/lib/pkgconfig);
    #    echo "::debug $(pkg-config --libs --cflags chafa)"
    
    - uses: actions/checkout@v4
      with:
        ref: ghaction

    #  working-directory: ./chafa-sys/
    #  run: >
    #    mkdir -p ./vendor
    #    && cd ./vendor
    #    && git clone https://gitlab.gnome.org/GNOME/glib.git
    #- name: Build glib
    #  working-directory: ./chafa-sys/vendor/glib
    #  run: >
    #    sudo meson setup _build
    #    && sudo meson compile -C _build
    #    && sudo meson install -C _build
    
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
