name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    # - name: Install chafa for dynamic linking
    #   run: >
    #     sudo apt-get install chafa &&
    #     sudo ldconfig &&
    #     ls /usr/local/bin | grep chafa
    - uses: actions/checkout@v4
    - name: Install tools for building C
      run: pipx install meson
    - name: Build glib
      working-directory: ./vendor/glib
      run: >
        cd vendor/glib
        && meson setup _build
        && meson compile -C _build
        && meson install -C _build
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
