name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    # - name: Install chafa
    #   run: >
    #     sudo apt-get install chafa;
    #     sudo ldconfig;
    
    - name: Install tools for building C
      run: >
        sudo pipx install meson
        && sudo apt-get install ninja-build
        
    - name: Download glib source
      run: >
        cd /tmp/ &&
        curl 'https://download.gnome.org/sources/glib/2.80/glib-2.80.0.tar.xz' -L -O &&
        ls

    - name: Build glib
      run: >
        cd /tmp/ &&
        tar xf glib-2.80.0.tar.xz &&
        cd glib-* &&
        meson setup _build &&
        meson compile -C _build &&
        meson install -C _build 

    #- name: Check chafa installation
    #  run: >
    #    export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig";
    #    echo $(ls /usr/local/lib/pkgconfig);
    #    echo "::debug $(pkg-config --libs --cflags chafa)"
    
    - uses: actions/checkout@v4
      with:
        ref: ghaction

    #  working-directory: ./chafa-sys/
    #  run: >
    #    mkdir -p ./vendor
    #    && cd ./vendor
    #    && git clone https://gitlab.gnome.org/GNOME/glib.git
    #- name: Build glib
    #  working-directory: ./chafa-sys/vendor/glib
    #  run: >
    #    sudo meson setup _build
    #    && sudo meson compile -C _build
    #    && sudo meson install -C _build
    
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
